// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: ProdFirebaseOptions.currentPlatform,
/// );
/// ```
class ProdFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'ProdFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'ProdFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8PQrKa4dd6BQ0EMG1DryVUmPSmj54FZ8',
    appId: '1:454166521983:web:947acb4f424a483a6b774a',
    messagingSenderId: '454166521983',
    projectId: 'put-me-in-coach-prod',
    authDomain: 'put-me-in-coach-prod.firebaseapp.com',
    storageBucket: 'put-me-in-coach-prod.firebasestorage.app',
    measurementId: 'G-WGSYZX38T8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMmYUkfrMJTRld6FvJmnJmPrcHs8DObaM',
    appId: '1:454166521983:android:27c750c579f64fb36b774a',
    messagingSenderId: '454166521983',
    projectId: 'put-me-in-coach-prod',
    storageBucket: 'put-me-in-coach-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDffwAU7oQVttrVEbF8lmx-7zu3nNXFY7Y',
    appId: '1:454166521983:ios:3740a1b8f2a9a9936b774a',
    messagingSenderId: '454166521983',
    projectId: 'put-me-in-coach-prod',
    storageBucket: 'put-me-in-coach-prod.firebasestorage.app',
    iosClientId: '454166521983-718isokvbrjiu4aah1slf676vc9nqb2f.apps.googleusercontent.com',
    iosBundleId: 'com.putmeincoach.putMeInCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDffwAU7oQVttrVEbF8lmx-7zu3nNXFY7Y',
    appId: '1:454166521983:ios:3740a1b8f2a9a9936b774a',
    messagingSenderId: '454166521983',
    projectId: 'put-me-in-coach-prod',
    storageBucket: 'put-me-in-coach-prod.firebasestorage.app',
    iosClientId: '454166521983-718isokvbrjiu4aah1slf676vc9nqb2f.apps.googleusercontent.com',
    iosBundleId: 'com.putmeincoach.putMeInCoach',
  );
}
