// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DevFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DevFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DevFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwVc9w-xxGXLOnzPA-2O5QDrpRhndeKwM',
    appId: '1:186499912115:web:e7e4233d0aa6ae0bcf3bc6',
    messagingSenderId: '186499912115',
    projectId: 'put-me-in-coach-dev',
    authDomain: 'put-me-in-coach-dev.firebaseapp.com',
    storageBucket: 'put-me-in-coach-dev.firebasestorage.app',
    measurementId: 'G-T5WB3SHR82',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSKuuAFB_Q7dUzAxP_46YxuIJHyQ8HQ0w',
    appId: '1:186499912115:android:239c2dc21106abf8cf3bc6',
    messagingSenderId: '186499912115',
    projectId: 'put-me-in-coach-dev',
    storageBucket: 'put-me-in-coach-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdo9T3ZajD06pnrU-FxX4N4EWkMkfJBAE',
    appId: '1:186499912115:ios:64fc71b162302db6cf3bc6',
    messagingSenderId: '186499912115',
    projectId: 'put-me-in-coach-dev',
    storageBucket: 'put-me-in-coach-dev.firebasestorage.app',
    iosClientId: '186499912115-b2de8e5226mb7m85f51l6nca4k42tk01.apps.googleusercontent.com',
    iosBundleId: 'com.putmeincoach.putMeInCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdo9T3ZajD06pnrU-FxX4N4EWkMkfJBAE',
    appId: '1:186499912115:ios:64fc71b162302db6cf3bc6',
    messagingSenderId: '186499912115',
    projectId: 'put-me-in-coach-dev',
    storageBucket: 'put-me-in-coach-dev.firebasestorage.app',
    iosClientId: '186499912115-b2de8e5226mb7m85f51l6nca4k42tk01.apps.googleusercontent.com',
    iosBundleId: 'com.putmeincoach.putMeInCoach',
  );
}
